apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aquasentinel
resources:
  - deployment.yaml
images:
  - name: aquasentinel
    newName: ghcr.io/cyberchopin/aquasentinel
    newTag: v0.2
